<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="p2.php" method="POST">
        <label for=""><i>login</i></label><br>
        <label for="">email</label>
        <input type="email" name="email"><br>
        <label for="">password</label>
        <input type="password" name="nom">
        <input type="submit" value="send" name="send">

    </form>
    
</body>
</html>